### ISSUE TITLE
Missing integerp check in accessors.lisp / get-pages

### ISSUE THREAD

**Issue by FrankRuben** [AlexCharlton/site-generator#11]
Hi Alex,
in accessors.lisp / get-pages you're accessing the `number` 2 times. The 1st call for building the 3rd argument of `subseq` are guarded by an `integerp` predicate, but the 2nd call for the 4th arg of `subseq` is not. You might like to guard this one too.
HTH and have fun with your generator, Frank

**Comment by AlexCharlton** [comment]
Hi Frank,

Thanks for pointing this out. If you check out the call to [`subseq`](http://www.ai.mit.edu/projects/iiip/doc/CommonLISP/HyperSpec/Body/acc_subseq.html) again, you see that it only has three arguments:

```lisp
(subseq pages start
	    (when (and (integerp number)
		       (<= (+ start number) (length pages)))
	      (+ start number)))
```
All of the references to `number` happen inside that `when`. So this is saying, when `number` is an integer (and `number + start` is within the total number of pages in the directory), then the `end` argument of `subseq` is `number + start`. Otherwise the `end` argument will be `nil`, which is already the default value for `subseq`. In other words, the `number` inside the `when` will never get evaluated if it isn't already an integer.

Hope this clears things up. Happy hacking :-)

**Comment by FrankRuben** [comment]
Hi Alex, 
sorry for the confusion - I should have checked harter and I assumed wrongly.
Thanks for taking care, Frank
